/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paquete_Interfaces;

import Paqute_Datos.AlquilerBD;
import Paquete_Clase.Alquiler;
import Paquete_Clase.Aseguradora;
import Paquete_Clase.Vehiculo;
import Paqute_Datos.VehiculoBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jhojan89
 */
public class AlquilerGUI extends javax.swing.JFrame {
Alquiler alq=new Alquiler();
AlquilerBD alq1=new AlquilerBD();
    /**
     * Creates new form AlquilerGUI
     */
    public AlquilerGUI() {
        initComponents();
        jPaneLVEHICULOS.setVisible(false);
        jPaneLVEHICULOSclase.setVisible(false);
        jPanelfactura.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPaneLVEHICULOS = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextbuscar = new javax.swing.JTextField();
        jButtbuscarvehiculo = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextcodcliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextfechasalida = new javax.swing.JTextField();
        jTextcodchofer = new javax.swing.JTextField();
        jTexcodclasevehi = new javax.swing.JTextField();
        jTextcodvehiculo = new javax.swing.JTextField();
        jButtconsltacliente = new javax.swing.JButton();
        jButtconsultavehiculo = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButtonCalcelar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTexfecharetorno = new javax.swing.JTextField();
        jTexproteccionrobo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTexcostodiario = new javax.swing.JTextField();
        jTextipoproteccion = new javax.swing.JTextField();
        jButtonGuardarAlquiler = new javax.swing.JButton();
        jChecreserva = new javax.swing.JCheckBox();
        jButtonBuscarAlquiler = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonaCtualizarAlquiler = new javax.swing.JButton();
        jTextcodalguiler = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPaneLVEHICULOSclase = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jButtBusclase1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanelfactura = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextcodfactura = new javax.swing.JTextField();
        jTextmonto = new javax.swing.JTextField();
        jTextFecha = new javax.swing.JTextField();
        jTextcodalquiler = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextcomentario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPaneLVEHICULOS.setBorder(javax.swing.BorderFactory.createTitledBorder("VEHICULOS"));
        jPaneLVEHICULOS.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPaneLVEHICULOS.setEnabled(false);

        jButton8.setText("Nuevo");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton10.setText("Salir");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Placa", "Color", "Fecha Ingrso", "Serial Chasis", "Serial Motor", "KM", "Litros", "Codigo Status", "Codigo modelo", "Codigo Poliza"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setText("Buscar Por");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Placa", "Chasis", "Todo" }));

        jButtbuscarvehiculo.setText("BUSCAR");
        jButtbuscarvehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtbuscarvehiculoActionPerformed(evt);
            }
        });

        jButton5.setText("Registrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneLVEHICULOSLayout = new javax.swing.GroupLayout(jPaneLVEHICULOS);
        jPaneLVEHICULOS.setLayout(jPaneLVEHICULOSLayout);
        jPaneLVEHICULOSLayout.setHorizontalGroup(
            jPaneLVEHICULOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneLVEHICULOSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addContainerGap(721, Short.MAX_VALUE))
            .addGroup(jPaneLVEHICULOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPaneLVEHICULOSLayout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jLabel8)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(28, 28, 28)
                    .addComponent(jButtbuscarvehiculo)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPaneLVEHICULOSLayout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 22, Short.MAX_VALUE)))
        );
        jPaneLVEHICULOSLayout.setVerticalGroup(
            jPaneLVEHICULOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneLVEHICULOSLayout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addGroup(jPaneLVEHICULOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton10)
                    .addComponent(jButton5))
                .addGap(5, 5, 5))
            .addGroup(jPaneLVEHICULOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPaneLVEHICULOSLayout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addGroup(jPaneLVEHICULOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtbuscarvehiculo)
                        .addComponent(jLabel8)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(36, Short.MAX_VALUE)))
        );

        jLabel10.setText("Codigo");

        jLabel11.setText("Codigo Cliente");

        jLabel12.setText("Codigo Vehiculo");

        jLabel13.setText("Codigo Clase Vehiculo");

        jLabel14.setText("Codigo Chofer");

        jLabel15.setText("Fecha Salida");

        jButtconsltacliente.setText("Cliente");
        jButtconsltacliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtconsltaclienteActionPerformed(evt);
            }
        });

        jButtconsultavehiculo.setText("Vehiculos");
        jButtconsultavehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtconsultavehiculoActionPerformed(evt);
            }
        });

        jButton11.setText("Clase Vehiculo");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Chofer");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Facturar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButtonCalcelar.setText("Cancelar");
        jButtonCalcelar.setEnabled(false);

        jLabel16.setText("Fecha Retorno");

        jLabel17.setText("Proteccion Robo");

        jLabel18.setText("Tipo Proteccion");

        jLabel19.setText("Costo Diario");

        jButtonGuardarAlquiler.setText("Guardar");
        jButtonGuardarAlquiler.setEnabled(false);
        jButtonGuardarAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarAlquilerActionPerformed(evt);
            }
        });

        jChecreserva.setText("Es Reservacion");

        jButtonBuscarAlquiler.setText("Buscar");
        jButtonBuscarAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarAlquilerActionPerformed(evt);
            }
        });

        jButton7.setText("Nuevo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setText("Consultar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButtonaCtualizarAlquiler.setText("Actualizar");
        jButtonaCtualizarAlquiler.setEnabled(false);
        jButtonaCtualizarAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaCtualizarAlquilerActionPerformed(evt);
            }
        });

        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jButton7)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonGuardarAlquiler)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonaCtualizarAlquiler)
                                .addGap(21, 21, 21)
                                .addComponent(jButton13)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCalcelar)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6))
                            .addComponent(jLabel15))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(399, 399, 399)
                                .addComponent(jChecreserva, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jTextcodalguiler, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(jButtonBuscarAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(128, 128, 128)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19))
                                        .addGap(23, 23, 23)))
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextipoproteccion, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(jTexcostodiario)
                                    .addComponent(jTexfecharetorno)
                                    .addComponent(jTexproteccionrobo))))
                        .addGap(218, 218, 218))))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(jLabel11)
                        .addComponent(jLabel10)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14))
                    .addGap(23, 23, 23)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jTextcodvehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtconsultavehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextfechasalida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                .addComponent(jTexcodclasevehi, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextcodchofer, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jTextcodcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtconsltacliente, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(460, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTexcostodiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarAlquiler)
                    .addComponent(jTextcodalguiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextipoproteccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexproteccionrobo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexfecharetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jChecreserva)
                .addGap(22, 22, 22)
                .addComponent(jLabel15)
                .addGap(30, 30, 30)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCalcelar)
                    .addComponent(jButtonGuardarAlquiler)
                    .addComponent(jButton13)
                    .addComponent(jButton7)
                    .addComponent(jButton9)
                    .addComponent(jButtonaCtualizarAlquiler)
                    .addComponent(jButton6))
                .addGap(57, 57, 57))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(jLabel10)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(jTextcodcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtconsltacliente, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jTextcodvehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtconsultavehiculo))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jTexcodclasevehi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton11))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jTextcodchofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton12))
                    .addGap(18, 18, 18)
                    .addComponent(jTextfechasalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(101, Short.MAX_VALUE)))
        );

        jPaneLVEHICULOSclase.setBorder(javax.swing.BorderFactory.createTitledBorder("ClLASE VEHICULOS"));
        jPaneLVEHICULOSclase.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPaneLVEHICULOSclase.setEnabled(false);

        jButton16.setText("Nuevo");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("Modificar");

        jButton18.setText("Salir");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jLabel32.setText("Buscar Por");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todo", "Codigo" }));

        jButtBusclase1.setText("Buscar");
        jButtBusclase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtBusclase1ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Costo Diario", "Costo Proteccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPaneLVEHICULOSclaseLayout = new javax.swing.GroupLayout(jPaneLVEHICULOSclase);
        jPaneLVEHICULOSclase.setLayout(jPaneLVEHICULOSclaseLayout);
        jPaneLVEHICULOSclaseLayout.setHorizontalGroup(
            jPaneLVEHICULOSclaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneLVEHICULOSclaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneLVEHICULOSclaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneLVEHICULOSclaseLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPaneLVEHICULOSclaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPaneLVEHICULOSclaseLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(15, 15, 15)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtBusclase1)))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jPaneLVEHICULOSclaseLayout.setVerticalGroup(
            jPaneLVEHICULOSclaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneLVEHICULOSclaseLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPaneLVEHICULOSclaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtBusclase1))
                .addGap(32, 32, 32)
                .addGroup(jPaneLVEHICULOSclaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPaneLVEHICULOSclaseLayout.createSequentialGroup()
                        .addComponent(jButton17)
                        .addGap(18, 18, 18)
                        .addComponent(jButton16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton18)))
                .addGap(50, 50, 50))
        );

        jPanelfactura.setBorder(javax.swing.BorderFactory.createTitledBorder("FACTURA"));

        jLabel1.setText("Codigo");

        jLabel2.setText("Monto");

        jLabel3.setText("Fecha");

        jLabel4.setText("Codigo Alquiler");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        jButton3.setText("Modificar");

        jLabel5.setText("Comentarios");

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelfacturaLayout = new javax.swing.GroupLayout(jPanelfactura);
        jPanelfactura.setLayout(jPanelfacturaLayout);
        jPanelfacturaLayout.setHorizontalGroup(
            jPanelfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelfacturaLayout.createSequentialGroup()
                .addGroup(jPanelfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelfacturaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5))
                    .addGroup(jPanelfacturaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelfacturaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanelfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelfacturaLayout.createSequentialGroup()
                                .addGroup(jPanelfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGroup(jPanelfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelfacturaLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextcodfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelfacturaLayout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addGroup(jPanelfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextcomentario, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextcodalquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanelfacturaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(69, 69, 69)
                                .addComponent(jTextmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelfacturaLayout.setVerticalGroup(
            jPanelfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelfacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextcodfactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanelfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanelfacturaLayout.createSequentialGroup()
                        .addComponent(jTextmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanelfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextcomentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextcodalquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelfactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPaneLVEHICULOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPaneLVEHICULOSclase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelfactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPaneLVEHICULOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPaneLVEHICULOSclase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtconsltaclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtconsltaclienteActionPerformed
        ClienteGUI cl=new ClienteGUI();
        cl.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtconsltaclienteActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jPaneLVEHICULOS.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
VehiculosGUI v=new VehiculosGUI();
v.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButtconsultavehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtconsultavehiculoActionPerformed
    jPaneLVEHICULOS.setVisible(true);
    jPaneLVEHICULOSclase.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButtconsultavehiculoActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
VehiculosGUI v=new VehiculosGUI();
v.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
jPaneLVEHICULOSclase.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
jPaneLVEHICULOSclase.setVisible(true); 
jPaneLVEHICULOS.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
ChoferGUI cho=new ChoferGUI();
cho.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
       jPanelfactura.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButtonGuardarAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarAlquilerActionPerformed
alq.setCodigoalquiler(jTextcodalguiler.getText());
alq.setFecha(jTextfechasalida.getText());
alq.setFecharetorno(jTexfecharetorno.getText());
alq.setTipoproteccion(jTexproteccionrobo.getText());
alq.setAcesorio(jTextipoproteccion.getText());
alq.setCodigocliente(jTextcodcliente.getText());
alq.setCostodiario(Double.parseDouble(jTexcostodiario.getText()));
alq.setCodigoVehiculo(jTextcodvehiculo.getText());
alq.setCodigoClasevehiculo(jTexcodclasevehi.getText());
alq.setCodigoConductor(jTextcodchofer.getText());
alq.setEsreserva("");
if(jChecreserva.isSelected()){
alq.setEsreserva("SI");

}
else{alq.setEsreserva("NO");}
alq1.InsertarAlquiler(alq.getCodigoalquiler(),alq.getCodigocliente(), alq.getFecha(), alq.getFecharetorno(), alq.getTipoproteccion(), alq.getAcesorio(), alq.getCostodiario(), alq.getEsreserva(), alq.getCodigoClasevehiculo(), alq.getCodigoVehiculo(), alq.getCodigoConductor());


// TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarAlquilerActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
jPanelfactura.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
alq.setCodigoFactura(Integer.parseInt(jTextcodfactura.getText()));
alq.setMonto(Double.parseDouble(jTextmonto.getText()));
alq.setFechafactura(jTextFecha.getText());
alq.setDescripcion(jTextcomentario.getText());
alq.setCodigoalquiler(jTextcodalquiler.getText());
alq1.insertarFactura(alq.getCodigoFactura(), alq.getMonto(), alq.getFechafactura(), alq.getDescripcion(), alq.getCodigoalquiler());



// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtbuscarvehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtbuscarvehiculoActionPerformed
        VehiculoBD v1=new VehiculoBD();
        Vehiculo vm=new Vehiculo();
        Vehiculo v=new Vehiculo();
        Aseguradora a1=new Aseguradora();
        DefaultTableModel t =(DefaultTableModel)jTable1.getModel();
        // t.addRow(new Object[WIDTH]);
        jTable1.setModel(t);
        if(jTextbuscar.getText().compareTo("") == 0 && jComboBox1.getSelectedItem().equals("Placa")|| jTextbuscar.getText().compareTo("") == 0&&jComboBox1.getSelectedItem().equals("Chasis")){
            JOptionPane.showMessageDialog(null, "Campos vasio");}

        else if(jComboBox1.getSelectedItem().equals("Placa") ){

            //String buscar=jTextbuscar.getText();

            try {
                String km;
                String litro;
                km=String.valueOf(v.getKilometrajeVeh());
                litro=String.valueOf(v.getLitrosVeh());
                for(Vehiculo vv : v1.mostrarVehiculoMatricula(jTextbuscar.getText())){
                    String Datos[]={String.valueOf(vv.getCodigoVeh()),vv.getPlacaVeh(),vv.getColorVeh(),vv.getFechaIngresoVeh(),vv.getSerialCarroseriaVeh(),
                        vv.getSerialmotorVeh(),km,litro,vv.getCodigoEstatus(),vm.getCodigoModelo(),vv.getCodigoPoliza()};
                    t.addRow(Datos);
                }   } catch (SQLException ex) {
                    Logger.getLogger(ConsultarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(jComboBox1.getSelectedItem().equals("Chasis") ){

                //DefaultTableModel t =(DefaultTableModel)jTable1.getModel();
                // t.addRow(new Object[WIDTH]);
                jTable1.setModel(t);

                try {
                    String km;
                    String litro;
                    km=String.valueOf(v.getKilometrajeVeh());
                    litro=String.valueOf(v.getLitrosVeh());
                    for(Vehiculo vv : v1.mostrarVehiculocod(jTextbuscar.getText())){

                        String Datos[]={String.valueOf(vv.getCodigoVeh()),vv.getPlacaVeh(),vv.getColorVeh(),vv.getFechaIngresoVeh(),vv.getSerialCarroseriaVeh(),
                            vv.getSerialmotorVeh(),km,litro,vv.getCodigoEstatus(),vm.getCodigoModelo(),vv.getCodigoPoliza()};
                        t.addRow(Datos);

                    }   } catch (SQLException ex) {
                        Logger.getLogger(ConsultarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

                else if (jComboBox1.getSelectedItem().equals("Todo") ){

                    //DefaultTableModel t =(DefaultTableModel)jTable1.getModel();
                    // t.addRow(new Object[WIDTH]);
                    jTable1.setModel(t);

                    try {
                        String km;
                        String litro;
                        km=String.valueOf(v.getKilometrajeVeh());
                        litro=String.valueOf(v.getLitrosVeh());
                        for(Vehiculo vv : v1.mostrarVehiculo()){
                            String Datos[]={String.valueOf(vv.getCodigoVeh()),vv.getPlacaVeh(),vv.getColorVeh(),vv.getFechaIngresoVeh(),vv.getSerialCarroseriaVeh(),
                                vv.getSerialmotorVeh(),km,litro,vv.getCodigoEstatus(),vm.getCodigoModelo(),vv.getCodigoPoliza()};
                            t.addRow(Datos);
                        }   } catch (SQLException ex) {
                            Logger.getLogger(ConsultarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }

                    // TODO add your handling code here:
    }//GEN-LAST:event_jButtbuscarvehiculoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        VehiculosGUI rv=new VehiculosGUI();
        rv.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtBusclase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtBusclase1ActionPerformed
        VehiculoBD vc5=new VehiculoBD();
        String costo="", costoprot="";

        DefaultTableModel t3 =(DefaultTableModel)jTable3.getModel();

        if(jTextField2.getText().compareTo("") == 0 && jComboBox3.getSelectedItem().equals("Codigo")){
            JOptionPane.showMessageDialog(null, "Campos vasio");}

        else if (jComboBox3.getSelectedItem().equals("Codigo") ){

            jTable3.setModel(t3);

            try {

                for(Vehiculo vc : vc5.mostrarVehiculoClaseCodigo(jTextField2.getText())){
                    String Datos[]={vc.getCodigoClase(), vc.getCodigoClase(),costo.valueOf(vc.getCostoDiario()), costoprot.valueOf(vc.getCostoDiario())};
                    //t2.addRow(new Object[0]);
                    t3.addRow(Datos);

                }   } catch (SQLException ex) {
                    Logger.getLogger(ConsultarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
            if (jComboBox3.getSelectedItem().equals("Todo") ){

                try {

                    for(Vehiculo vc : vc5.mostrarVehiculoClase()){
                        String Datos[]={vc.getCodigoClase(), vc.getCodigoClase(),costo.valueOf(vc.getCostoDiario()), costoprot.valueOf(vc.getCostoDiario())};
                        t3.addRow(Datos);
                        t3.addRow(new Object[0]);
                    }   } catch (SQLException ex) {
                        Logger.getLogger(ConsultarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }         // TODO add your handling code here:
    }//GEN-LAST:event_jButtBusclase1ActionPerformed
public void BuscarAlquiler(){
    Alquiler a=new Alquiler();
try {
   
            a= AlquilerBD.BuscarAlquiler(jTextcodalguiler.getText());
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR:" + e.getMessage());
        }
        if (a != null) {
            String reserva;
            jTextcodalguiler.setText(String.valueOf(a.getCodigoalquiler()));
            jTextcodcliente.setText(a.getCodigocliente());
            jTextcodvehiculo.setText(a.getCodigoVehiculo());
            jTexcodclasevehi.setText(a.getCodigoClasevehiculo());
            jTextcodchofer.setText(a.getCodigoConductor());
            jTextfechasalida.setText(a.getFecha());
            jTexcostodiario.setText(String.valueOf(a.getCostodiario()));
            jTextipoproteccion.setText(a.getTipoproteccion());
            jTexproteccionrobo.setText(a.getAcesorio());
            jTexfecharetorno.setText(a.getFecharetorno());
            if(a.getEsreserva().equals("SI")){
            jChecreserva.setSelected(true);
            
            
            }
           
        jButtonaCtualizarAlquiler.setEnabled(true);
            jButtonCalcelar.setEnabled(true);
        
        
        
        }

        else {
            JOptionPane.showMessageDialog(null, "No exite");
           jButtonaCtualizarAlquiler.setEnabled(false);
            jTextcodalguiler.setText("");
            jButtonCalcelar.setEnabled(false);
            jTextcodalguiler.setEditable(true);
            }




}
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
Consultar_Alquiler ac =new Consultar_Alquiler();
ac.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
jTextcodalguiler.setEnabled(false);
jButtonBuscarAlquiler.setEnabled(false);
jButtonGuardarAlquiler.setEnabled(true);
jButtonCalcelar.setEnabled(true);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButtonBuscarAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarAlquilerActionPerformed
if (jTextcodalguiler.getText().compareTo("") != 0) {
            int result = JOptionPane.showConfirmDialog(
                    this, "Deseas Buscar el Alquiler para Modificarlo?",
                    "Mensaje..!!",
                    JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                BuscarAlquiler();
                jButtonaCtualizarAlquiler.setEnabled(true);
            }
            if (result == JOptionPane.NO_OPTION) {
                
                
                //jButtactualizar.setEnabled(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese Codigo del Alquiler a Buscar");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarAlquilerActionPerformed

    private void jButtonaCtualizarAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaCtualizarAlquilerActionPerformed

        try {
            Alquiler a;
            a = AlquilerBD.BuscarAlquiler(jTextcodalguiler.getText());
            a.setCodigocliente(jTextcodcliente.getText());
            a.setCodigoVehiculo(jTextcodvehiculo.getText());
            a.setCodigoClasevehiculo(jTexcodclasevehi.getText());
            a.setCodigoConductor(jTextcodchofer.getText());
            a.setFecha(jTextfechasalida.getText());
            a.setFecharetorno(jTexfecharetorno.getText());
            a.setTipoproteccion(jTextipoproteccion.getText());
            a.setAcesorio(jTexproteccionrobo.getText());
            a.setCostodiario(Double.valueOf(jTexcostodiario.getText()));
            a.setEsreserva(jChecreserva.getText());
        
           
            AlquilerBD.ActualizarAlquiler(a);
            JOptionPane.showMessageDialog(null, " [ Datos Actualizados ]");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error BD: " + e.getMessage());
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_jButtonaCtualizarAlquilerActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlquilerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlquilerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlquilerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlquilerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlquilerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtBusclase1;
    private javax.swing.JButton jButtbuscarvehiculo;
    private javax.swing.JButton jButtconsltacliente;
    private javax.swing.JButton jButtconsultavehiculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonBuscarAlquiler;
    private javax.swing.JButton jButtonCalcelar;
    private javax.swing.JButton jButtonGuardarAlquiler;
    private javax.swing.JButton jButtonaCtualizarAlquiler;
    private javax.swing.JCheckBox jChecreserva;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPaneLVEHICULOS;
    private javax.swing.JPanel jPaneLVEHICULOSclase;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelfactura;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTexcodclasevehi;
    private javax.swing.JTextField jTexcostodiario;
    private javax.swing.JTextField jTexfecharetorno;
    private javax.swing.JTextField jTexproteccionrobo;
    private javax.swing.JTextField jTextFecha;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextbuscar;
    private javax.swing.JTextField jTextcodalguiler;
    private javax.swing.JTextField jTextcodalquiler;
    private javax.swing.JTextField jTextcodchofer;
    private javax.swing.JTextField jTextcodcliente;
    private javax.swing.JTextField jTextcodfactura;
    private javax.swing.JTextField jTextcodvehiculo;
    private javax.swing.JTextField jTextcomentario;
    private javax.swing.JTextField jTextfechasalida;
    private javax.swing.JTextField jTextipoproteccion;
    private javax.swing.JTextField jTextmonto;
    // End of variables declaration//GEN-END:variables
}
