/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paquete_Interfaces;

import Paqute_Datos.AseguradoraBD;
import Paquete_Clase.Aseguradora;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jhojan89
 */
public class AseguradoraGUI extends javax.swing.JFrame {
Aseguradora as=new Aseguradora();
AseguradoraBD asbd=new AseguradoraBD();
    /**
     * Creates new form Aseguradora
     */
    public AseguradoraGUI() {
        initComponents();
       
        jPanel4.setVisible(false);
        jPanel7.setVisible(false);
        jButtocerrartabla.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTecodasegu = new javax.swing.JTextField();
        jTefechafin = new javax.swing.JTextField();
        jTefechainicio = new javax.swing.JTextField();
        jTefechaemision = new javax.swing.JTextField();
        jTecodpoliza = new javax.swing.JTextField();
        jButtguardar1 = new javax.swing.JButton();
        jButtbuscar1 = new javax.swing.JButton();
        jButtnuevo1 = new javax.swing.JButton();
        jBueditar1 = new javax.swing.JButton();
        jButtcancelar1 = new javax.swing.JButton();
        jButconsultar1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButtocerrartabla = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtguardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButtnuevo = new javax.swing.JButton();
        jBueditar = new javax.swing.JButton();
        jButtcancelar = new javax.swing.JButton();
        jButconsultar = new javax.swing.JButton();
        jTeaseguradora = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTetelaseguradora = new javax.swing.JTextField();
        jTecodaseguradora = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTefaxaseguradora = new javax.swing.JTextField();
        jButtbuscar = new javax.swing.JButton();
        jTediraseguradora = new javax.swing.JTextField();
        jTeemailaseguradora = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 800));

        jLabel11.setText("Codigo");

        jLabel12.setText("Fecha Emicion");

        jLabel13.setText("Fecha Inicio");

        jLabel3.setText("Fecha Fin");

        jLabel4.setText("Codigo Aseguradora");

        jButtguardar1.setText("Guardar");
        jButtguardar1.setEnabled(false);
        jButtguardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtguardar1ActionPerformed(evt);
            }
        });

        jButtbuscar1.setText("Borrar");
        jButtbuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtbuscar1ActionPerformed(evt);
            }
        });

        jButtnuevo1.setText("Nuevo");
        jButtnuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtnuevo1ActionPerformed(evt);
            }
        });

        jBueditar1.setText("Editar");
        jBueditar1.setEnabled(false);
        jBueditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBueditar1ActionPerformed(evt);
            }
        });

        jButtcancelar1.setText("cancelar");
        jButtcancelar1.setEnabled(false);
        jButtcancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtcancelar1ActionPerformed(evt);
            }
        });

        jButconsultar1.setText("CONSULTAR");
        jButconsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButconsultar1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigo", "fecha emicion", "fecha inicio", "fecha vencimiento", "codigo aseguradora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(0, 204, 204));
        jScrollPane2.setViewportView(jTable2);
        jTable2.getAccessibleContext().setAccessibleParent(jTable2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jButtocerrartabla.setText("Cerrar tabla");
        jButtocerrartabla.setEnabled(false);
        jButtocerrartabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtocerrartablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTefechaemision)
                                .addComponent(jTefechainicio)
                                .addComponent(jTefechafin, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTecodasegu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTecodpoliza, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtbuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtnuevo1)
                        .addGap(26, 26, 26)
                        .addComponent(jButtguardar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBueditar1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtcancelar1)
                        .addGap(18, 18, 18)
                        .addComponent(jButconsultar1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtocerrartabla))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTecodpoliza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtbuscar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTefechaemision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTefechainicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jTefechafin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTecodasegu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtnuevo1)
                    .addComponent(jBueditar1)
                    .addComponent(jButtcancelar1)
                    .addComponent(jButconsultar1)
                    .addComponent(jButtguardar1)
                    .addComponent(jButtocerrartabla))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Poliza", jPanel1);

        jPanel3.setPreferredSize(new java.awt.Dimension(800, 800));

        jButtguardar.setText("Guardar");
        jButtguardar.setEnabled(false);
        jButtguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtguardarActionPerformed(evt);
            }
        });

        jLabel5.setText("Email");

        jButtnuevo.setText("Nuevo");
        jButtnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtnuevoActionPerformed(evt);
            }
        });

        jBueditar.setText("Editar");
        jBueditar.setEnabled(false);
        jBueditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBueditarActionPerformed(evt);
            }
        });

        jButtcancelar.setText("cancelar");
        jButtcancelar.setEnabled(false);
        jButtcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtcancelarActionPerformed(evt);
            }
        });

        jButconsultar.setText("CONSULTAR");
        jButconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButconsultarActionPerformed(evt);
            }
        });

        jLabel9.setText("ASEGURADORA");

        jLabel2.setText("Fax");

        jLabel1.setText("Telefono");

        jLabel8.setText("Codigo");

        jLabel10.setText("Direccion");

        jButtbuscar.setText("Borrar");
        jButtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtbuscarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Aseguradora", "Direccion", "Telefono", "Fax", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Cerrar Tabla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(408, 408, 408)
                        .addComponent(jButton1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTeemailaseguradora, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel9))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTecodaseguradora)
                                    .addComponent(jTeaseguradora)
                                    .addComponent(jTefaxaseguradora, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTetelaseguradora)
                                    .addComponent(jTediraseguradora, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButtnuevo)
                        .addGap(18, 18, 18)
                        .addComponent(jButtguardar)
                        .addGap(18, 18, 18)
                        .addComponent(jBueditar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtcancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButconsultar))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTecodaseguradora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTeaseguradora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTefaxaseguradora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jTetelaseguradora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTediraseguradora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTeemailaseguradora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtguardar)
                    .addComponent(jButtnuevo)
                    .addComponent(jBueditar)
                    .addComponent(jButtcancelar)
                    .addComponent(jButconsultar))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Aseguradora", jPanel3);

        jPanel5.setBackground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(0, 51, 153));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButconsultarActionPerformed
        jPanel7.setVisible(true);

        DefaultTableModel t =(DefaultTableModel)jTable1.getModel();
        // t.addRow(new Object[WIDTH]);
        jTable1.setModel(t);

        try {
            //JOptionPane.showMessageDialog(null, uc.getNombre());

            for(Aseguradora cc : asbd.MostrarAseguradoras()){
                String Datos[]={cc.getCodigoAseguradora(),cc.getNombreAseguradora(),cc.getDireccionAseguradora(),cc.getTelefonoAseguradora(),cc.getFaxAseguradora(),cc.getEmailseguradora()};
                t.addRow(Datos);
            }   } catch (SQLException ex) {
                Logger.getLogger(ConsultarUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }

            // TODO add your handling code here:
    }//GEN-LAST:event_jButconsultarActionPerformed

    private void jButtcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtcancelarActionPerformed
        limpiar();
        jTecodaseguradora.setEnabled(true);
        jButtguardar.setEnabled(false);
        jButtnuevo.setEnabled(true);
        jButtcancelar.setEnabled(false);
        jButtbuscar.setEnabled(true);
        jBueditar.setEnabled(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtcancelarActionPerformed

    private void jBueditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBueditarActionPerformed
        Aseguradora a;
        try {
            a = AseguradoraBD.BuscarAseguradora(jTecodaseguradora.getText());
            a.setNombreAseguradora(jTeaseguradora.getText());
            a.setFaxAseguradora(jTefaxaseguradora.getText());
            a.setTelefonoAseguradora(jTetelaseguradora.getText());
            a.setDireccionAseguradora(jTediraseguradora.getText());
            a.setEmailseguradora(jTeemailaseguradora.getText());

            AseguradoraBD.ActualizarAseguradora(a);
            JOptionPane.showMessageDialog(null, " [ Datos Actualizados ]");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error BD: " + e.getMessage());
        }
    }//GEN-LAST:event_jBueditarActionPerformed

    private void jButtnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtnuevoActionPerformed
        jBueditar.setEnabled(false);
        jButtbuscar.setEnabled(false);
        jTecodaseguradora.setEditable(false);
        jButtcancelar.setEnabled(true);
        jButtguardar.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtnuevoActionPerformed

    private void jButtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtbuscarActionPerformed
        if (jTecodaseguradora.getText().compareTo("") != 0) {
            int result = JOptionPane.showConfirmDialog(
                this, "Deseas Buscar  Aseguradora para Modificarlo?",
                "Mensaje..!!",
                JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                BuscarAseguradora();
                jBueditar.setEnabled(true);
            }
            if (result == JOptionPane.NO_OPTION) {

                jBueditar.setEnabled(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese Codigo de la Aseguradora a Buscar");
        }         // TODO add your ha        // TODO add your handling code here:
    }//GEN-LAST:event_jButtbuscarActionPerformed

    private void jButtguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtguardarActionPerformed

        as.setCodigoAseguradora(jTecodaseguradora.getText());
        as.setNombreAseguradora(jTeaseguradora.getText());
        as.setDireccionAseguradora(jTediraseguradora.getText());
        as.setTelefonoAseguradora(jTetelaseguradora.getText());
        as.setFaxAseguradora(jTefaxaseguradora.getText());
        as.setEmailseguradora(jTeemailaseguradora.getText());
        asbd.InsertarAseguradora(as.getCodigoAseguradora(), as.getNombreAseguradora(), as.getDireccionAseguradora(), as.getTelefonoAseguradora(), as.getFaxAseguradora(), as.getEmailseguradora());

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtguardarActionPerformed

    private void jButtocerrartablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtocerrartablaActionPerformed
        jPanel4.setVisible(false);
        jButtocerrartabla.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButtocerrartablaActionPerformed

    private void jButconsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButconsultar1ActionPerformed
        jPanel4.setVisible(true);
        jButtocerrartabla.setVisible(true);
        jButtocerrartabla.setEnabled(true);
        DefaultTableModel t =(DefaultTableModel)jTable2.getModel();
        // t.addRow(new Object[WIDTH]);
        jTable2.setModel(t);

        try {
            //JOptionPane.showMessageDialog(null, uc.getNombre());

            for(Aseguradora cc : asbd.MostrarPoliza()){
                String Datosp[]={cc.getCodigoPoliza(),cc.getFechaEmicion(),cc.getFechaInicio(),cc.getFechaFin(),cc.getCodigoAseguradora()};
                t.addRow(Datosp);

            }

        } catch (SQLException ex) {
            Logger.getLogger(ConsultarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButconsultar1ActionPerformed

    private void jButtcancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtcancelar1ActionPerformed
        limpiar();
        jTecodaseguradora.setEditable(true);
        jTecodaseguradora.setEnabled(true);
        jButtbuscar.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtcancelar1ActionPerformed

    private void jBueditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBueditar1ActionPerformed
        Aseguradora p;
        try {
            p = AseguradoraBD.BuscarPoliza(jTecodpoliza.getText());
            p.setFechaEmicion(jTefechaemision.getText());
            p.setFechaInicio(jTefechainicio.getText());
            p.setFechaFin(jTefechafin.getText());
            p.setCodigoAseguradora(jTecodasegu.getText());

            AseguradoraBD.ActualizarPoliza(p);
            JOptionPane.showMessageDialog(null, " [ Datos Actualizados ]");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error BD: " + e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jBueditar1ActionPerformed

    private void jButtnuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtnuevo1ActionPerformed
        jButtbuscar1.setEnabled(false);
        jTecodpoliza.setEditable(false);
        jButtguardar1.setEnabled(true);
        jButtcancelar1.setEnabled(true);
        jButtnuevo1.setEnabled(false);
    }//GEN-LAST:event_jButtnuevo1ActionPerformed

    private void jButtbuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtbuscar1ActionPerformed
        if (jTecodpoliza.getText().compareTo("") != 0) {
            int result = JOptionPane.showConfirmDialog(
                this, "Deseas Buscar  Poliza para Modificarlo?",
                "Mensaje..!!",
                JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                BuscarPoliza();
                jBueditar1.setEnabled(true);
            }
            if (result == JOptionPane.NO_OPTION) {

                jBueditar1.setEnabled(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese Codigo de la poliza a Buscar");
        } // TODO add your handling code here:
    }//GEN-LAST:event_jButtbuscar1ActionPerformed

    private void jButtguardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtguardar1ActionPerformed
        as.setCodigoPoliza(jTecodpoliza.getText());
        as.setFechaEmicion(jTefechaemision.getText());
        as.setFechaInicio(jTefechainicio.getText());
        as.setFechaFin(jTefechafin.getText());
        as.setCodigoAseguradora(jTecodasegu.getText());
        asbd.insertarPoliza(as.getCodigoPoliza(), as.getFechaEmicion(), as.getFechaInicio(), as.getFechaFin(), as.getCodigoAseguradora());
    }//GEN-LAST:event_jButtguardar1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jPanel7.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    public void BuscarAseguradora(){
try {
            as=AseguradoraBD.BuscarAseguradora(jTecodaseguradora.getText());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR:" + e.getMessage());
        }
        if (as != null) {
            jTecodaseguradora.setText(String.valueOf(as.getCodigoAseguradora() ));
            
jTeaseguradora.setText(as.getNombreAseguradora());
jTediraseguradora.setText(as.getDireccionAseguradora());
jTetelaseguradora.setText(as.getTelefonoAseguradora());
jTefaxaseguradora.setText(as.getFaxAseguradora());
jTeemailaseguradora.setText(as.getEmailseguradora());
           
        jBueditar.setEnabled(true);
            jButtcancelar.setEnabled(true);
        
        
        
        }

         else {
           
            JOptionPane.showMessageDialog(null, "No exite");
            jBueditar.setEnabled(false);
            
            jButtcancelar.setEnabled(false);
            jTecodaseguradora.setEditable(true);
        }
    }
    public void BuscarPoliza(){
try {
            as=AseguradoraBD.BuscarPoliza(jTecodpoliza.getText());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR:" + e.getMessage());
        }
        if (as != null) {
            jTecodpoliza.setText(String.valueOf(as.getCodigoPoliza()));
            
jTefechaemision.setText(as.getFechaEmicion());
jTefechainicio.setText(as.getFechaInicio());
jTefechafin.setText(as.getFechaFin());
jTecodasegu.setText(as.getCodigoAseguradora());

           
        jBueditar.setEnabled(true);
            jButtcancelar.setEnabled(true);
        
        
        
        }

         else {
           
            JOptionPane.showMessageDialog(null, "No exite");
            jBueditar1.setEnabled(false);
            
            jButtcancelar1.setEnabled(false);
            jTecodpoliza.setEditable(true);
        }}
    public void limpiar(){
jTecodaseguradora.setText("");
jTeaseguradora.setText("");
jTediraseguradora.setText("");
jTetelaseguradora.setText("");
jTefaxaseguradora.setText("");
jTeemailaseguradora.setText("");
jTecodpoliza.setText("");
jTefechaemision.setText("");
jTefechafin.setText("");
jTefechainicio.setText("");
jTecodasegu.setText("");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AseguradoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AseguradoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AseguradoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AseguradoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AseguradoraGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBueditar;
    private javax.swing.JButton jBueditar1;
    private javax.swing.JButton jButconsultar;
    private javax.swing.JButton jButconsultar1;
    private javax.swing.JButton jButtbuscar;
    private javax.swing.JButton jButtbuscar1;
    private javax.swing.JButton jButtcancelar;
    private javax.swing.JButton jButtcancelar1;
    private javax.swing.JButton jButtguardar;
    private javax.swing.JButton jButtguardar1;
    private javax.swing.JButton jButtnuevo;
    private javax.swing.JButton jButtnuevo1;
    private javax.swing.JButton jButtocerrartabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTeaseguradora;
    private javax.swing.JTextField jTecodasegu;
    private javax.swing.JTextField jTecodaseguradora;
    private javax.swing.JTextField jTecodpoliza;
    private javax.swing.JTextField jTediraseguradora;
    private javax.swing.JTextField jTeemailaseguradora;
    private javax.swing.JTextField jTefaxaseguradora;
    private javax.swing.JTextField jTefechaemision;
    private javax.swing.JTextField jTefechafin;
    private javax.swing.JTextField jTefechainicio;
    private javax.swing.JTextField jTetelaseguradora;
    // End of variables declaration//GEN-END:variables
}
