/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paquete_Interfaces;

import Paqute_Datos.ChoferBD;
import Paquete_Clase.Chofer;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jhojan89
 */
public class ChoferGUI extends javax.swing.JFrame {

    /**
     * Creates new form ChoferGUI
     */
   Chofer chof=new Chofer(); 
   ChoferBD chofbd=new ChoferBD();
   
    public ChoferGUI() {
        initComponents();
        jPaneconsultarchofer.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTlicenciachof = new javax.swing.JTextField();
        jTecatchof = new javax.swing.JTextField();
        jTedirchof = new javax.swing.JTextField();
        jTetelchof = new javax.swing.JTextField();
        jTeemailchof = new javax.swing.JTextField();
        jTexnomchof = new javax.swing.JTextField();
        jTecodchof = new javax.swing.JTextField();
        jTeapellchof = new javax.swing.JTextField();
        jTecedchof = new javax.swing.JTextField();
        jTeedadchof = new javax.swing.JTextField();
        jButtoguardar = new javax.swing.JButton();
        jBuconsultarchof = new javax.swing.JButton();
        jPaneconsultarchofer = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField17 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jBuscarconductor = new javax.swing.JButton();
        jButtbuscar = new javax.swing.JButton();
        jButtnuevo = new javax.swing.JButton();
        jBueditar = new javax.swing.JButton();
        jButtcancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CHOFER");
        setBackground(new java.awt.Color(0, 51, 255));
        setPreferredSize(new java.awt.Dimension(858, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 153));
        jLabel11.setText("REGISTRAR CHOFER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Codigo");

        jLabel2.setText("Direccion");

        jLabel3.setText("Nombre");

        jLabel4.setText("Categoria Licencia");

        jLabel5.setText("Apellido");

        jLabel6.setText("cedula");

        jLabel7.setText("Licencia Conducir");

        jLabel8.setText("Edad");

        jLabel9.setText("Telefono");

        jLabel10.setText("Email");

        jButtoguardar.setText("Guardar");
        jButtoguardar.setEnabled(false);
        jButtoguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoguardarActionPerformed(evt);
            }
        });

        jBuconsultarchof.setText("CONSULTAR");
        jBuconsultarchof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuconsultarchofActionPerformed(evt);
            }
        });

        jPaneconsultarchofer.setBorder(javax.swing.BorderFactory.createTitledBorder("CHOFER"));
        jPaneconsultarchofer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel12.setText("Buscar Por");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Codigo", "Cedula", "Todo" }));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cedula", "nombre", "apellido", "Edad", "Licencia", "Categoria", "Direccion", "telefono", "Email"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton16.setText("Nuevo");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("Modificar");

        jButton18.setText("Salir");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jBuscarconductor.setText("Buscar");
        jBuscarconductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarconductorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneconsultarchoferLayout = new javax.swing.GroupLayout(jPaneconsultarchofer);
        jPaneconsultarchofer.setLayout(jPaneconsultarchoferLayout);
        jPaneconsultarchoferLayout.setHorizontalGroup(
            jPaneconsultarchoferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneconsultarchoferLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneconsultarchoferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneconsultarchoferLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBuscarconductor)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
                    .addGroup(jPaneconsultarchoferLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton17)
                        .addGap(18, 18, 18)
                        .addComponent(jButton16)
                        .addGap(18, 18, 18)
                        .addComponent(jButton18))))
        );
        jPaneconsultarchoferLayout.setVerticalGroup(
            jPaneconsultarchoferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneconsultarchoferLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPaneconsultarchoferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBuscarconductor))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPaneconsultarchoferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton16)
                    .addComponent(jButton18)
                    .addComponent(jButton17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtbuscar.setText("jButton3");
        jButtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtbuscarActionPerformed(evt);
            }
        });

        jButtnuevo.setText("Nuevo");
        jButtnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtnuevoActionPerformed(evt);
            }
        });

        jBueditar.setText("Editar");
        jBueditar.setEnabled(false);
        jBueditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBueditarActionPerformed(evt);
            }
        });

        jButtcancelar.setText("cancelar");
        jButtcancelar.setEnabled(false);
        jButtcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtcancelarActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPaneconsultarchofer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTexnomchof))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                    .addComponent(jTeapellchof, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTecedchof))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTeedadchof, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTecodchof, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(23, 23, 23)
                                .addComponent(jTlicenciachof))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTecatchof))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addComponent(jTedirchof, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTeemailchof, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(jTetelchof))))
                        .addContainerGap(442, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtnuevo)
                        .addGap(34, 34, 34)
                        .addComponent(jButtoguardar)
                        .addGap(30, 30, 30)
                        .addComponent(jBueditar)
                        .addGap(27, 27, 27)
                        .addComponent(jButtcancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jBuconsultarchof)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jTlicenciachof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTecodchof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jTecatchof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexnomchof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jTedirchof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTeapellchof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(jTetelchof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTecedchof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jTeedadchof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jTeemailchof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtnuevo)
                    .addComponent(jBueditar)
                    .addComponent(jButtcancelar)
                    .addComponent(jBuconsultarchof)
                    .addComponent(jButtoguardar)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jPaneconsultarchofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
      jPaneconsultarchofer.setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jBuconsultarchofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuconsultarchofActionPerformed
         jPaneconsultarchofer.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jBuconsultarchofActionPerformed

    private void jButtoguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoguardarActionPerformed
        chof.setCodigoChofer(jTecodchof.getText());
        chof.setCedulaChofer(jTecedchof.getText());
        chof.setNombreChofer(jTexnomchof.getText());
        chof.setApellidoChofer(jTeapellchof.getText());
        chof.setEdadChofer(Integer.parseInt(jTeedadchof.getText()));
        chof.setLicenciaCoonducirChofer(jTlicenciachof.getText());
        chof.setCategorialicenciaChofer(Integer.parseInt(jTecatchof.getText()));
        chof.setDireccionChofer(jTedirchof.getText());
        chof.setTelefonoChofer(jTetelchof.getText());
        chof.setEmailChofer(jTeemailchof.getText());
        chofbd.AgregarChofer(chof.getCodigoChofer(), chof.getCedulaChofer(), chof.getNombreChofer(), chof.getApellidoChofer(), chof.getEdadChofer(), chof.getLicenciaCoonducirChofer(), chof.getCategorialicenciaChofer(), chof.getDireccionChofer(),
            chof.getTelefonoChofer(),chof.getEmailChofer());
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButtoguardarActionPerformed

    private void jBuscarconductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarconductorActionPerformed
 if(jTextField17.getText().compareTo("") == 0 && jComboBox2.getSelectedItem().equals("Codigo")|| jTextField17.getText().compareTo("") == 0&&jComboBox2.getSelectedItem().equals("Cedula")){
            JOptionPane.showMessageDialog(null, "Campos vasio");}

        else if(jComboBox2.getSelectedItem().equals("Codigo") ){

            DefaultTableModel t =(DefaultTableModel)jTable2.getModel();
            // t.addRow(new Object[WIDTH]);
            jTable2.setModel(t);

            //String buscar=jTextField17.getText();

        
            try {
                //JOptionPane.showMessageDialog(null, uc.getNombre());
                
                for(Chofer cc : chofbd.MostrarChofercod(jTextField17.getText())){
                    String edad =String.valueOf(cc.getEdadChofer());
                    String cat =String.valueOf(cc.getCategorialicenciaChofer());
                    
                    String Datos[]={cc.getCodigoChofer(),cc.getCedulaChofer(),cc.getNombreChofer(),cc.getApellidoChofer(),
                           edad,cc.getLicenciaCoonducirChofer(),cat,cc.getDireccionChofer(),cc.getTelefonoChofer(),cc.getTelefonoChofer(),cc.getEmailChofer()};
                    t.addRow(Datos);
                }   } catch (SQLException ex) {
                    Logger.getLogger(ConsultarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(jComboBox2.getSelectedItem().equals("Cedula") ){

                DefaultTableModel t =(DefaultTableModel)jTable2.getModel();
                // t.addRow(new Object[WIDTH]);
                jTable2.setModel(t);

                ///String buscar=jTextField17.getText();

                try {
                    //JOptionPane.showMessageDialog(null, uc.getNombre());

                    for(Chofer cc : chofbd.MostrarChofercedula(jTextField17.getText())){
                        String edad =String.valueOf(cc.getEdadChofer());
                    String cat =String.valueOf(cc.getCategorialicenciaChofer());
                       String Datos[]={cc.getCodigoChofer(),cc.getCedulaChofer(),cc.getNombreChofer(),cc.getApellidoChofer(),
                           edad,cc.getLicenciaCoonducirChofer(),cat,cc.getDireccionChofer(),cc.getTelefonoChofer(),cc.getTelefonoChofer(),cc.getEmailChofer()};
                    t.addRow(Datos);
                    
                    }   } catch (SQLException ex) {
                        Logger.getLogger(ConsultarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                    } }
                else if (jComboBox2.getSelectedItem().equals("Todo") ){

                    DefaultTableModel t =(DefaultTableModel)jTable2.getModel();
                    // t.addRow(new Object[WIDTH]);
                    jTable2.setModel(t);

                    try {
                        //JOptionPane.showMessageDialog(null, uc.getNombre());

                        for(Chofer cc : chofbd.mostrarChofer()){
                            String edad =String.valueOf(cc.getEdadChofer());
                    String cat =String.valueOf(cc.getCategorialicenciaChofer());
                           String Datos[]={cc.getCodigoChofer(),cc.getCedulaChofer(),cc.getNombreChofer(),cc.getApellidoChofer(),
                           edad,cc.getLicenciaCoonducirChofer(),cat,cc.getDireccionChofer(),cc.getTelefonoChofer(),cc.getTelefonoChofer(),cc.getEmailChofer()
                           };
                    t.addRow(Datos);
                        }   } catch (SQLException ex) {
                            Logger.getLogger(ConsultarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

// TODO add your handling code here:
    }//GEN-LAST:event_jBuscarconductorActionPerformed

    public void nuevo(){
jTecodchof.setEnabled(false);
      
        jBueditar.setEnabled(false);
        jButtcancelar.setEnabled(true);
        jButtbuscar.setEnabled(false);
        jButtnuevo.setEnabled(false);
        
}
    private void jButtnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtnuevoActionPerformed
        nuevo();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtnuevoActionPerformed

    private void jBueditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBueditarActionPerformed
        Chofer ch;
        try {
            ch = ChoferBD.BuscarChofer(jTecodchof.getText());
            ch.setNombreChofer(jTexnomchof.getText());
            ch.setApellidoChofer(jTeapellchof.getText());
            ch.setCedulaChofer(jTecedchof.getText());
            ch.setTelefonoChofer(jTetelchof.getText());
            ch.setLicenciaCoonducirChofer(jTlicenciachof.getText());
            ch.setEdadChofer(Integer.parseInt(jTeedadchof.getText()));
            ch.setDireccionChofer(jTedirchof.getText());
            ch.setEmailChofer(jTeemailchof.getText());
            ch.setCategorialicenciaChofer(Integer.parseInt(jTecatchof.getText()));
            ch.setEdadChofer(Integer.parseInt(jTeedadchof.getText()));
            ChoferBD.ActualizarChofer(ch);
            JOptionPane.showMessageDialog(null, " [ Datos Actualizados ]");
       } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error BD: " + e.getMessage());
        }
    }//GEN-LAST:event_jBueditarActionPerformed

    private void jButtcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtcancelarActionPerformed
        //limpiar();
        jTecodchof.setEnabled(true);
        jButtoguardar.setEnabled(false);
        jButtnuevo.setEnabled(true);
        jButtcancelar.setEnabled(false);
        jButtbuscar.setEnabled(true);
        jBueditar.setEnabled(false);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtcancelarActionPerformed

    private void jButtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtbuscarActionPerformed
if (jTecodchof.getText().compareTo("") != 0) {
            int result = JOptionPane.showConfirmDialog(
                    this, "Deseas Buscar al Chofer para Modificarlo?",
                    "Mensaje..!!",
                    JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                BuscarChofer();
                jBueditar.setEnabled(true);
            }
            if (result == JOptionPane.NO_OPTION) {
                
                
                jBueditar.setEnabled(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese Codigo del Chofer a Buscar");
} }
public void BuscarChofer(){
try {
            chof= ChoferBD.BuscarChofer(jTecodchof.getText());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR:" + e.getMessage());
        }
        if (chof != null) {
            jTecodchof.setText(String.valueOf(chof.getCodigoChofer()));
            jTexnomchof.setText(chof.getNombreChofer());
            jTeapellchof.setText(chof.getApellidoChofer());
            jTecedchof.setText(chof.getCedulaChofer());
            jTlicenciachof.setText(chof.getLicenciaCoonducirChofer());
            jTecatchof.setText(String.valueOf(chof.getCategorialicenciaChofer()));
            jTetelchof.setText(chof.getTelefonoChofer());
            jTedirchof.setText(chof.getDireccionChofer());
            jTeemailchof.setText(chof.getEmailChofer());
            jTeedadchof.setText(String.valueOf(chof.getEdadChofer()));
           
        jBueditar.setEnabled(true);
            jButtcancelar.setEnabled(true);
        
        
        
        }

         else {
           jBueditar.setEnabled(false);
            
            jButtcancelar.setEnabled(false);
            jTecodchof.setEditable(true);
            JOptionPane.showMessageDialog(null, "No exite");}
        


// TODO add your handling code here:
    }//GEN-LAST:event_jButtbuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoferGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoferGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoferGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoferGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChoferGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBuconsultarchof;
    private javax.swing.JButton jBueditar;
    private javax.swing.JButton jBuscarconductor;
    private javax.swing.JButton jButtbuscar;
    private javax.swing.JButton jButtcancelar;
    private javax.swing.JButton jButtnuevo;
    private javax.swing.JButton jButtoguardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPaneconsultarchofer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTeapellchof;
    private javax.swing.JTextField jTecatchof;
    private javax.swing.JTextField jTecedchof;
    private javax.swing.JTextField jTecodchof;
    private javax.swing.JTextField jTedirchof;
    private javax.swing.JTextField jTeedadchof;
    private javax.swing.JTextField jTeemailchof;
    private javax.swing.JTextField jTetelchof;
    private javax.swing.JTextField jTexnomchof;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTlicenciachof;
    // End of variables declaration//GEN-END:variables
}
