/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paquete_Interfaces;

import Paqute_Datos.UsuarioBD;
import Paquete_Clase.Usuario;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Jhojan89
 */
public class UsuarioGUI extends javax.swing.JFrame {
    UsuarioBD ub=new UsuarioBD();
    Usuario us=new Usuario();
    
    
    /**
     * Creates new form Usuario
     */
    public UsuarioGUI() {
        initComponents();
        jCombotipo.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtoguardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfCedulausuario = new javax.swing.JTextField();
        jtfapellidoUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfnomusuario = new javax.swing.JTextField();
        jtfcodigousuario1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfrepetirpassword = new javax.swing.JTextField();
        jtfpassworkUsuario = new javax.swing.JTextField();
        jtfTelefonoUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtnuevo = new javax.swing.JButton();
        jBueditar = new javax.swing.JButton();
        jButtcancelar = new javax.swing.JButton();
        jButconsultar = new javax.swing.JButton();
        jButtbuscar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jCombotipo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Usuario");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("usuario"));

        jPanel4.setBackground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 868, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(0, 51, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 255));

        jButtoguardar.setText("Guardar");
        jButtoguardar.setEnabled(false);
        jButtoguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoguardarActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo usuario");

        jtfUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfUsuarioKeyReleased(evt);
            }
        });

        jLabel5.setText("Cedula");

        jLabel4.setText("Usuario");

        jtfapellidoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfapellidoUsuarioKeyTyped(evt);
            }
        });

        jLabel3.setText("Apellido");

        jLabel2.setText("Nombre");

        jtfnomusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfnomusuarioActionPerformed(evt);
            }
        });
        jtfnomusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfnomusuarioKeyTyped(evt);
            }
        });

        jtfcodigousuario1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtfcodigousuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfcodigousuario1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Codigo");

        jtfpassworkUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfpassworkUsuarioActionPerformed(evt);
            }
        });

        jLabel7.setText("Telefono");

        jLabel8.setText("Passwork");

        jLabel9.setText("Repetir Password");

        jButtnuevo.setText("Nuevo");
        jButtnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtnuevoActionPerformed(evt);
            }
        });

        jBueditar.setText("Editar");
        jBueditar.setEnabled(false);
        jBueditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBueditarActionPerformed(evt);
            }
        });

        jButtcancelar.setText("cancelar");
        jButtcancelar.setEnabled(false);
        jButtcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtcancelarActionPerformed(evt);
            }
        });

        jButconsultar.setText("CONSULTAR");
        jButconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButconsultarActionPerformed(evt);
            }
        });

        jButtbuscar.setText("Buscar");
        jButtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtbuscarActionPerformed(evt);
            }
        });

        jCombotipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Abministrador", "Otro" }));
        jCombotipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombotipoActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jtfcodigousuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jtfCedulausuario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtfapellidoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtfnomusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtfTelefonoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtfrepetirpassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                        .addComponent(jtfpassworkUsuario, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCombotipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtnuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtoguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBueditar)
                        .addGap(27, 27, 27)
                        .addComponent(jButtcancelar)
                        .addGap(41, 41, 41)
                        .addComponent(jButconsultar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfcodigousuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfnomusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCombotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfapellidoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfpassworkUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfCedulausuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jtfTelefonoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfrepetirpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtoguardar)
                    .addComponent(jButtnuevo)
                    .addComponent(jBueditar)
                    .addComponent(jButtcancelar)
                    .addComponent(jButconsultar)
                    .addComponent(jButton1))
                .addContainerGap(324, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCombotipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombotipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCombotipoActionPerformed

    private void jButtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtbuscarActionPerformed
        if (jtfcodigousuario1.getText().compareTo("") != 0) {
            int result = JOptionPane.showConfirmDialog(
                this, "Deseas Buscar al Cliente para Modificarlo?",
                "Mensaje..!!",
                JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                BuscarUsuario();
                jBueditar.setEnabled(true);
            }
            if (result == JOptionPane.NO_OPTION) {

                jBueditar.setEnabled(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese Codigo del Cliente a Buscar");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButtbuscarActionPerformed

    private void jButconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButconsultarActionPerformed
        ConsultarUsuario consu=new ConsultarUsuario();
        consu.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButconsultarActionPerformed

    private void jButtcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtcancelarActionPerformed
        limpiar();
        jtfcodigousuario1.setEnabled(true);
        jButtoguardar.setEnabled(false);
        jButtnuevo.setEnabled(true);
        jButtcancelar.setEnabled(false);
        jButtbuscar.setEnabled(true);
        jBueditar.setEnabled(false);
        jCombotipo.setVisible(true);
        jTextField1.setVisible(true);
        jCombotipo.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtcancelarActionPerformed

    private void jBueditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBueditarActionPerformed
        Usuario u;
        try {
            u = UsuarioBD.BuscarUsuario(jtfcodigousuario1.getText());
            u.setNombre(jtfnomusuario.getText());
            u.setApellido(jtfapellidoUsuario.getText());
            u.setCedula(jtfCedulausuario.getText());
            u.setUsuario(jtfUsuario.getText());
            u.setTelefono(jtfTelefonoUsuario.getText());
            u.setPasswork(jtfpassworkUsuario.getText());
            u.setTipoUsuario(jTextField1.getText());
            UsuarioBD.ActualizarUsuario(u);
            JOptionPane.showMessageDialog(null, " [ Datos Actualizados ]");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error BD: " + e.getMessage());
        }
    }//GEN-LAST:event_jBueditarActionPerformed

    private void jButtnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtnuevoActionPerformed
        nuevo();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtnuevoActionPerformed

    private void jtfpassworkUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfpassworkUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfpassworkUsuarioActionPerformed

    private void jtfcodigousuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfcodigousuario1ActionPerformed
        jtfcodigousuario1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jtfcodigousuario1ActionPerformed

    private void jButtoguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoguardarActionPerformed
        if(jtfnomusuario.getText().compareTo("") !=0 && jtfapellidoUsuario.getText().compareTo("")!=0
            && jtfCedulausuario.getText().compareTo("")!=0&& jtfUsuario.getText().compareTo("")!=0&&jtfTelefonoUsuario.getText().compareTo("")!=0
            &&  jtfpassworkUsuario.getText().compareTo("")!=0){
            UsuarioBD ub=new UsuarioBD();
            //c.abrirConexion();
            us.setNombre(jtfnomusuario.getText());
            us.setUsuario(jtfUsuario.getText());
            us.setCodigousuario(jtfcodigousuario1.getText());
            us.setCedula(jtfCedulausuario.getText());
            us.setTelefono(jtfTelefonoUsuario.getText());
            if(jCombotipo.getSelectedItem().equals("Abministrador")){

                us.setTipoUsuario("Abministrador");
            }
            else if(jCombotipo.getSelectedItem().equals("Otro")){us.setTipoUsuario("Otro");}
            us.setPasswork(jtfpassworkUsuario.getText());
            us.setApellido(jtfapellidoUsuario.getText());

            ub.insertarEmpleado(us.getCodigousuario(),us.getNombre(), us.getApellido(),us.getCedula(), us.getTelefono(), us.getUsuario(),us.getTipoUsuario(), us.getPasswork());

        }
        else{JOptionPane.showMessageDialog(null,"Llene todos los Campos  ");}
    }//GEN-LAST:event_jButtoguardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtfnomusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfnomusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfnomusuarioActionPerformed

    private void jtfnomusuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfnomusuarioKeyTyped
if (!String.valueOf(evt.getKeyChar()).matches("[a-zA-Z]|\\s")) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jtfnomusuarioKeyTyped

    private void jtfapellidoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfapellidoUsuarioKeyTyped
if (!String.valueOf(evt.getKeyChar()).matches("[a-zA-Z]|\\s")) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jtfapellidoUsuarioKeyTyped

    private void jtfUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfUsuarioKeyReleased
if (!String.valueOf(evt.getKeyChar()).matches("[a-zA-Z]|\\s")) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUsuarioKeyReleased
public void BuscarUsuario(){
try {
            us= UsuarioBD.BuscarUsuario(jtfcodigousuario1.getText());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR:" + e.getMessage());
        }
        if (us != null) {
            jtfcodigousuario1.setText(String.valueOf(us.getCodigousuario()));
            jtfnomusuario.setText(us.getNombre());
            jtfapellidoUsuario.setText(us.getApellido());
            jtfCedulausuario.setText(us.getCedula());
            jtfUsuario.setText(us.getUsuario());
            jtfTelefonoUsuario.setText(us.getTelefono());
            jtfpassworkUsuario.setText(us.getPasswork());
            jTextField1.setText(us.getTipoUsuario());
           
        jBueditar.setEnabled(true);
            jButtcancelar.setEnabled(true);
        
        
        
        }

        else {
            JOptionPane.showMessageDialog(null, "No exite");
           jBueditar.setEnabled(false);
            jtfcodigousuario1.setText("");
            jButtcancelar.setEnabled(false);
            jtfcodigousuario1.setEditable(true);
            }
        
}

    
         //To change body of generated methods, choose Tools | Templates.
    







public void limpiar(){
jtfcodigousuario1.setText("");
jtfnomusuario.setText("");
jtfapellidoUsuario.setText("");
jtfCedulausuario.setText("");
jtfTelefonoUsuario.setText("");
jtfUsuario.setText("");
jtfpassworkUsuario.setText("");

}
public void nuevo(){
jtfcodigousuario1.setEnabled(false);
        jButtoguardar.setEnabled(true);
        jBueditar.setEnabled(false);
        jButtcancelar.setEnabled(true);
        jButtbuscar.setEnabled(false);
        jButtnuevo.setEnabled(false);
        jCombotipo.setVisible(true);
        jTextField1.setVisible(false);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBueditar;
    private javax.swing.JButton jButconsultar;
    private javax.swing.JButton jButtbuscar;
    private javax.swing.JButton jButtcancelar;
    private javax.swing.JButton jButtnuevo;
    private javax.swing.JButton jButtoguardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jCombotipo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jtfCedulausuario;
    private javax.swing.JTextField jtfTelefonoUsuario;
    private javax.swing.JTextField jtfUsuario;
    private javax.swing.JTextField jtfapellidoUsuario;
    private javax.swing.JTextField jtfcodigousuario1;
    private javax.swing.JTextField jtfnomusuario;
    private javax.swing.JTextField jtfpassworkUsuario;
    private javax.swing.JTextField jtfrepetirpassword;
    // End of variables declaration//GEN-END:variables
}
